#!/bin/zsh

# Editor
# export EDITOR="${commands[nvim]:-$EDITOR}"
export EDITOR=nvim
export CVSEDITOR="${EDITOR}"
export GIT_EDITOR="${EDITOR}"
# For GUI
export VISUAL="${EDITOR}"

# True color
export COLORTERM=truecolor

# Word split
export WORDCHARS=''
export DIRSTACKSIZE=100

# XDG PATHS
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
# export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Custom zsh completions path
export GENCOMP_DIR=$XDG_CONFIG_HOME/zsh/completions
export CUSTOM_FPATH="$XDG_CONFIG_HOME/zsh/completions"
export fpath=($fpath $CUSTOM_FPATH)

# Homebrew
export HOMEBREW_NO_AUTO_UPDATE=true
# export HOMEBREW_CASK_OPTS=--no-quarantine

# Language
export LANGUAGE="en_US.UTF-8"
export LANG="${LANGUAGE}"
export LC_ALL="${LANGUAGE}"
export LC_CTYPE="${LANGUAGE}"

# https://github.com/ogham/exa/blob/adfee28fb9bb6f491c822ba4506fafef03909945/Vagrantfile#L163
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

# ipython
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"

# jupyter
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"

# bat
export BAT_CONFIG_PATH="$XDG_CONFIG_HOME/bat/config"

# starship
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/zsh/themes/starship.toml"

# dotdrop
export DOTDROP_CONFIG="$HOME/Dropbox/my-dotfiles/config.yaml"
