# Powerlevel10k instant prompt
if [[ -r "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# NVM
export NVM_DIR="$HOME/.config/nvm"
export NVM_COMPLETION=true
export NVM_LAZY_LOAD=true
export NVM_LAZY_LOAD_EXTRA_COMMANDS=('nvim')

### Start of Zinit's installer chunk
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
source "${ZINIT_HOME}/zinit.zsh"
autoload -Uz _zinit
 (( ${+_comps} )) && _comps[zinit]=_zinit

# ZSH_AUTOSUGGEST
# "ctrl + →" doing the forward-word, and "→" getting to the end of prompt line
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
ZSH_AUTOSUGGEST_COMPLETION_IGNORE='( |man |pikaur -S )*'
# Don't show suggestions after abbreviations
ZSH_AUTOSUGGEST_HISTORY_IGNORE=${(j:|:)${(k)ABBR_REGULAR_USER_ABBREVIATIONS}}
ZSH_AUTOSUGGEST_COMPLETION_IGNORE=${ZSH_AUTOSUGGEST_HISTORY_IGNORE}
export FORGIT_FZF_DEFAULT_OPTS="
--exact
--border
--cycle
--reverse
--height '80%'
"

# forgit
forgit_add=fga
forgit_diff=fgd
forgit_log=fglo
forgit_ignore=fgi
forgit_stash_show=fgss


# Zsh-you-should-use
YSU_MODE=ALL  # or BESTMATCH
YSU_MESSAGE_POSITION="after"
YSU_MESSAGE_FORMAT="$(tput setaf 1)Hey! I found this %alias_type for %command: %alias$(tput sgr0)"

# Z.lua
# _ZL_ECHO=1  # display new directory name after cd
# _ZL_MATCH_MODE=1  # enhanced matching
# _ZL_ADD_ONCE=1  # only add path if the $PWD is changed

# ZSHZ
ZSHZ_ECHO=1

# Vi Mode
# Mode-sensitive cursor styling
# The recognized style words are steady, blinking, block, underline and bar.
MODE_CURSOR_VIINS="#00ff00 blinking bar"
MODE_CURSOR_REPLACE="$MODE_CURSOR_VIINS #ff0000"
MODE_CURSOR_VICMD="green block"
MODE_CURSOR_SEARCH="#ff00ff steady underline"
MODE_CURSOR_VISUAL="$MODE_CURSOR_VICMD steady bar"
MODE_CURSOR_VLINE="$MODE_CURSOR_VISUAL #00ffff"
# Mode in prompt
MODE_INDICATOR_VIINS='%F{15}<%F{8}INSERT<%f'
MODE_INDICATOR_VICMD='%F{10}<%F{2}NORMAL<%f'
MODE_INDICATOR_REPLACE='%F{9}<%F{1}REPLACE<%f'
MODE_INDICATOR_SEARCH='%F{13}<%F{5}SEARCH<%f'
MODE_INDICATOR_VISUAL='%F{12}<%F{4}VISUAL<%f'
MODE_INDICATOR_VLINE='%F{12}<%F{4}V-LINE<%f'

# plugins
zinit light-mode for \
    softmoth/zsh-vim-mode \
    olets/zsh-abbr \
    agkozak/zsh-z
#     skywind3000/z.lua \

zinit wait="2" lucid light-mode for \
    MichaelAquilina/zsh-you-should-use \
    hlissner/zsh-autopair \
    wfxr/forgit \
    lukechilds/zsh-nvm # This load nvm on first use of node, npm, etc
#     Aloxaf/gencomp

zinit light-mode for \
    blockf \
        zsh-users/zsh-completions \
    atclone="dircolors -b LS_COLORS > c.zsh" atpull='%atclone' pick='c.zsh' nocompile'!' \
        trapd00r/LS_COLORS

# OMZ
zinit wait="2" lucid for \
    OMZP::git-extras \
    OMZP::git \
    OMZP::sudo \
    OMZP::systemd \
    OMZL::clipboard.zsh

# remove Git completion provided by Homebrew
[ -e /usr/local/share/zsh/site-functions/git-completion.bash ] && rm /usr/local/share/zsh/site-functions/git-completion.bash
[ -e /usr/local/share/zsh/site-functions/_git ] && rm /usr/local/share/zsh/site-functions/_git

# zinit ice as"program" mv"*cht.sh -> cht.sh" pick"cht.sh"
# zinit snippet https://cht.sh/:cht.sh

zinit ice mv=":zsh -> _cht" as="completion"
zinit snippet https://cheat.sh/:zsh

zinit as="completion" for \
    OMZP::docker/_docker \
    OMZP::fd/_fd \
    esc/conda-zsh-completion

zinit svn for \
    OMZP::pip \
    OMZP::extract \

# special plugins
zpcompinit; zpcdreplay

for config in $XDG_CONFIG_HOME/zsh/*.zsh; do
    source $config
done

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh

zinit light-mode for \
    zdharma-continuum/fast-syntax-highlighting \
    Aloxaf/fzf-tab \
    zsh-users/zsh-autosuggestions \
    OMZP::colored-man-pages

bindkey '^ ' autosuggest-execute

# themes
: ${THEME:=p10k}

case $THEME in
    starship)
        eval "$(starship init zsh)" || logwarn "failed loading starship."
        ;;
    p10k)
        source $XDG_CONFIG_HOME/zsh/themes/p10k.zsh
        zinit ice depth=1; zinit light romkatv/powerlevel10k
        ;;
esac

### End of Zinit's installer chunk

# exec -l fish "$@"
