if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source "$HOME/.zinit/bin/zinit.zsh"
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history
setopt appendhistory

# NVM
export NVM_DIR="$HOME/.config/nvm"
export NVM_COMPLETION=true
export NVM_LAZY_LOAD=true
export NVM_LAZY_LOAD_EXTRA_COMMANDS=('nvim')

# conda
[ -d  "$HOME/miniconda3/bin" ] && export PATH="$HOME/miniconda3/bin:$PATH"  # commented out by conda initialize
# Rust
export PATH="$HOME/.cargo/bin:$PATH"
export CARGO_HOME="$HOME/.cargo"

alias ..='\cd ..'
alias ...='\cd ../..'
alias ....='\cd ../../..'
alias .....='\cd ../../../..'
alias cd.='\cd ..'
alias cd..='\cd ..'
alias ls='ls --color=auto'
alias ll='ls --group-directories-first -l'
alias la='ls --group-directories-first -l --all'
alias l='ll'
if (( $+commands[exa] )); then
    alias ls='exa --icons'
    alias ll='ls -lgbh --git'
    alias lg='ll -G'    # List by grid
    alias llg='ll -G'
    alias la='ls -a'
    alias lla='ll -a'
    alias lag='llg -a'
    alias ldot='ll -d .*'
    alias lss='ll -s size'
    alias lst='ll -s modified'
    alias lt='ls --tree'
fi
# alias cl='cd ..;ls'
function chpwd() {
  ls
}

alias pssh=parallel-ssh
alias pscp=parallel-scp
alias prsync=parallel-rsync
alias pnuke=parallel-nuke
alias pslurp=parallel-slurp

alias rm='rm -iv'
alias mv='mv -iv'
alias rd='rmdir'
alias md='mkdir -v -p'
if (( $+commands[nvim] )); then
    alias vi="nvim"
    alias vim="nvim"
fi
# ZSH_AUTOSUGGEST
# "ctrl + →" doing the forward-word, and "→" getting to the end of prompt line
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
ZSH_AUTOSUGGEST_COMPLETION_IGNORE='( |man |pikaur -S )*'
# Don't show suggestions after abbreviations
ZSH_AUTOSUGGEST_HISTORY_IGNORE=${(j:|:)${(k)ABBR_REGULAR_USER_ABBREVIATIONS}}
ZSH_AUTOSUGGEST_COMPLETION_IGNORE=${ZSH_AUTOSUGGEST_HISTORY_IGNORE}

# forgit
forgit_add=fga
forgit_diff=fgd
forgit_log=fglo
forgit_ignore=fgi
FORGIT_FZF_DEFAULT_OPTS="--height '80%'"
forgit_stash_show=fgss

# Zsh-you-should-use
YSU_MODE=ALL  # or BESTMATCH
YSU_MESSAGE_POSITION="after"
YSU_MESSAGE_FORMAT="$(tput setaf 1)Hey! I found this %alias_type for %command: %alias$(tput sgr0)"

# ZSHZ
ZSHZ_ECHO=1

# Vi Mode
# Mode-sensitive cursor styling
# The recognized style words are steady, blinking, block, underline and bar.
MODE_CURSOR_VIINS="#00ff00 blinking bar"
MODE_CURSOR_REPLACE="$MODE_CURSOR_VIINS #ff0000"
MODE_CURSOR_VICMD="green block"
MODE_CURSOR_SEARCH="#ff00ff steady underline"
MODE_CURSOR_VISUAL="$MODE_CURSOR_VICMD steady bar"
MODE_CURSOR_VLINE="$MODE_CURSOR_VISUAL #00ffff"
# Mode in prompt
MODE_INDICATOR_VIINS='%F{15}<%F{8}INSERT<%f'
MODE_INDICATOR_VICMD='%F{10}<%F{2}NORMAL<%f'
MODE_INDICATOR_REPLACE='%F{9}<%F{1}REPLACE<%f'
MODE_INDICATOR_SEARCH='%F{13}<%F{5}SEARCH<%f'
MODE_INDICATOR_VISUAL='%F{12}<%F{4}VISUAL<%f'
MODE_INDICATOR_VLINE='%F{12}<%F{4}V-LINE<%f'

zinit as="completion" for \
    esc/conda-zsh-completion

zinit ice as"completion"
zinit snippet https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/docker/_docker

# plugins
zinit light-mode for \
    olets/zsh-abbr \
    agkozak/zsh-z \
    softmoth/zsh-vim-mode
#     skywind3000/z.lua \

zinit wait="2" lucid light-mode for \
    MichaelAquilina/zsh-you-should-use \
    hlissner/zsh-autopair \
    wfxr/forgit \
    lukechilds/zsh-nvm # This load nvm on first use of node, npm, etc

zinit light-mode for \
    blockf \
        zsh-users/zsh-completions \
    atclone="dircolors -b LS_COLORS > c.zsh" atpull='%atclone' pick='c.zsh' nocompile'!' \
        trapd00r/LS_COLORS

# OMZ
zinit wait="2" lucid for \
    OMZP::git-extras \
    OMZP::git \
    OMZP::sudo \
    OMZP::systemd \
    OMZL::clipboard.zsh

zinit as="completion" for \
    OMZP::docker/_docker \
    OMZP::fd/_fd \
    esc/conda-zsh-completion

zinit svn for \
    OMZP::pip \
    OMZP::extract \

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# special plugins
zpcompinit; zpcdreplay

source $HOME/.completion.zsh
source $HOME/.fzf.configs.zsh

zinit light-mode for \
    Aloxaf/fzf-tab \
    zsh-users/zsh-autosuggestions \
    zdharma/fast-syntax-highlighting \
    OMZP::colored-man-pages

bindkey '^ ' autosuggest-execute

# zinit load zdharma/history-search-multi-word

zinit ice depth=1; zinit light romkatv/powerlevel10k
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
